version: '3.8'

services:
  backend:
    build: ../backend
    expose:
      - "8000"
    networks:
      - internal-net
    volumes:
        - ../backend/data.txt:/app/data.txt

  frontend:
    build: ../frontend
    expose:
      - "80"
    networks:
      - internal-net
    depends_on:
      - backend

  proxy:
    image: nginx:stable-alpine
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - internal-net
    depends_on:
      - frontend

networks:
  internal-net:
    driver: bridge
